# Generated by Django 6.0.4 on 2026-06-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_code', models.CharField(max_length=50)),
                ('billing_period', models.CharField(max_length=50)),
                ('usage_litres', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='Unpaid', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Warning', 'Warning'), ('Offline', 'Offline')], default='Active', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='meter_qrcodes/')),
                ('valve_open', models.BooleanField(default=True)),
                ('current_flow_rate', models.FloatField(default=0)),
                ('total_usage_litres', models.FloatField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('device_token', models.CharField(blank=True, max_length=100, null=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('Leakage', 'Leakage'), ('Faulty Meter', 'Faulty Meter'), ('Wrong Bill', 'Wrong Bill'), ('General Support', 'General Support')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('nin', models.CharField(max_length=50, unique=True)),
                ('land_status', models.CharField(choices=[('Ownership', 'Full Ownership'), ('Leased', 'Leased')], default='Ownership', max_length=20)),
                ('mobile_password', models.CharField(blank=True, max_length=128, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_account_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount_paid', models.FloatField()),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(default='Successful', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_litres', models.FloatField()),
                ('flow_rate', models.FloatField(default=0)),
                ('reading_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.meter')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Faulty', 'Faulty'), ('Stolen', 'Stolen'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Upgrade', 'Upgrade'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('replacement_date', models.DateTimeField(auto_now_add=True)),
                ('new_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_replacements', to='dashboard.meter')),
                ('old_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_replacements', to='dashboard.meter')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='WaterCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_litres', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.meter')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wateruser'),
        ),
    ]
