# Generated by Django 6.0.4 on 2026-06-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='resolved',
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
