# Generated by Django 6.0.4 on 2026-06-23 22:13

import django.db.models.deletion
from django.db import migrations, models
from datetime import date


def create_tariff_categories(apps, schema_editor):
    Tariff = apps.get_model('dashboard', 'Tariff')
    Meter = apps.get_model('dashboard', 'Meter')

    domestic, _ = Tariff.objects.get_or_create(
        name='Domestic',
        defaults={
            'rate_per_litre': 5,
            'effective_from': date(2026, 6, 24),
            'active': True,
        },
    )
    Tariff.objects.filter(id=domestic.id).update(active=True)

    for name in ('Commercial', 'Industrial'):
        tariff, _ = Tariff.objects.get_or_create(
            name=name,
            defaults={
                'rate_per_litre': 5,
                'effective_from': date(2026, 6, 24),
                'active': True,
            },
        )
        Tariff.objects.filter(id=tariff.id).update(active=True)

    Meter.objects.filter(tariff__isnull=True).update(tariff=domestic)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='dashboard.tariff'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Airtel Money', 'Airtel Money'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=100, unique=True),
        ),
        migrations.RunPython(create_tariff_categories, migrations.RunPython.noop),
    ]
