# Generated by Django 6.0.4 on 2026-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_meter_tariff_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='customer_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
