# Generated by Django 6.0.4 on 2026-06-23 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_supportrequest_customer_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='MTN MoMo', max_length=30)),
                ('reference_id', models.UUIDField(unique=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('provider_phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transactions', to='dashboard.bill')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transactions', to='dashboard.meter')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_money_transaction', to='dashboard.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
