# Generated by Django 6.0.4 on 2026-06-24 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mobilemoneytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='billing_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
